{{- if and .Values.fsm.gatewayApi.enabled (not .Values.fsm.ingress.enabled ) (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fsm.gateway.serviceAccountName" . }}
  namespace: {{ .Values.gwy.metadata.namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  {{- with .Values.fsm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}