apiVersion: v2
name: fsm
description: A Helm chart to install the FSM(Flomesh Service Mesh) on Kubernetes
home: https://flomesh.io
icon: https://charts.flomesh.io/flomesh.png
kubeVersion: ">= 1.19.0-0"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.8-ubi.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.8-ubi.6"

keywords:
  - kubernetes
  - helm
  - service mesh
  - ingress
  - gateway api
  - olm
  - traffic management
  - pipy
  - sidecar
  - proxy

maintainers:
  - name: Eric
    email: reaver@flomesh.io

sources:
  - https://github.com/flomesh-io/fsm
  - https://github.com/flomesh-io/pipy

dependencies:
- name: tpls
  version: 0.1.1
  repository: file://../tpls
- name: cert-manager
  version: 1.7.2
  repository: https://charts.jetstack.io
  condition: certManager.enabled

annotations:
  charts.openshift.io/name: fsm
#  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: added
      description: Support SNI
    - kind: added
      description: Support per namespace TLS config for NamespacedIngress
    - kind: added
      description: Add POD annotations to NamespacedIngress CRD
    - kind: added
      description: Make the upstream SSL port of SNI is configurable 
    - kind: changed
      description: Re-structure the values.yaml of fsm chart
    - kind: changed
      description: Speed up the startup time
    - kind: changed
      description: Add prefix fsm- to fsm resources
    - kind: fixed
      description: Handle empty server names in case SNI is enabled
  artifacthub.io/links: |
    - name: source
      url: https://github.com/flomesh-io/fsm
    - name: support
      url: https://github.com/flomesh-io/fsm/issues