apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy-nonroot
  namespace: flomesh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pipy-nonroot
      flomesh.io/app: pipy-nonroot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pipy-nonroot
        flomesh.io/app: pipy-nonroot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: flomesh.io/app
                  operator: In
                  values:
                  - pipy-nonroot
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: flomesh/pipy:0.90.2-13-debug-nonroot
        imagePullPolicy: Always
        name: pipy-nonroot
        command:
          - /busybox/sleep
          - infinity
        resources:
          limits:
            cpu: "2"
            memory: 1G
          requests:
            cpu: 500m
            memory: 128M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault