apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.connector.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  {{ .Values.fsm.configmaps.connector.filename }}: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceNamespace: {{ include "fsm.namespace" . }}
