{{- if not .Values.fsm.repo.preProvision.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "fsm.namespace" . }}
  name: {{ .Values.fsm.flb.secretName }}
type: Opaque
data:
  baseUrl: {{ .Values.fsm.flb.baseUrl | b64enc }}
  username: {{ .Values.fsm.flb.username | b64enc }}
  password: {{ .Values.fsm.flb.password | b64enc }}
{{- end }}