{{- if .Values.fsm.logging.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "fsm.namespace" . }}
  name: {{ .Values.fsm.logging.secretName }}
type: Opaque
data:
  baseUrl: {{ .Values.fsm.logging.url | b64enc }}
  authorization: {{ .Values.fsm.logging.authorization | b64enc }}
{{- end }}