apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.manifests.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  default_proxyprofile.yaml: |-
{{ (.Files.Get "components/default_proxyprofile.yaml") | indent 4 }}
