apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.manifests.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  default_proxyprofile.yaml: |-
{{ (.Files.Get "components/default_proxyprofile.yaml") | indent 4 }}
  {{- if and .Values.fsm.gatewayApi.enabled (not .Values.fsm.ingress.enabled ) (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
  gateway-class.yaml: |-
{{ (.Files.Get "components/gateway-class.yaml") | indent 4 }}
  {{- end }}