apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.mesh.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  mesh_config.json: |-
    {
      "isManaged": false,

      "images": {
        "repository": "{{ .Values.fsm.image.repository }}",
        "pipyImage": {{ include "fsm.pipy.image.wo-repo" . | quote }},
        "proxyInitImage": {{ include "fsm.proxy-init.image.wo-repo" . | quote }},
        "klipperLbImage": {{ include "fsm.service-lb.image.wo-repo" . | quote }}
      },

      "repo": {
        "rootUrl": {{ include "fsm.repo-service.url" . | quote }}
      },

      "webhook": {
        "serviceName": "{{ .Values.fsm.services.webhook.name }}"
      },

      "ingress": {
        "enabled": {{ .Values.fsm.ingress.enabled }},
        "namespaced": {{ .Values.fsm.ingress.namespaced }},
        "http": {
          "enabled": {{ .Values.fsm.ingress.http.enabled }},
          "listen": {{ .Values.fsm.ingress.http.containerPort }}
        },
        "tls": {
          "enabled": {{ .Values.fsm.ingress.tls.enabled }},
          "listen": {{ .Values.fsm.ingress.tls.containerPort }},
          "mTLS": {{ .Values.fsm.ingress.tls.mTLS }},
          "sslPassthrough": {
            "enabled": {{ .Values.fsm.ingress.tls.sslPassthrough.enabled }},
            "upstreamPort": {{ .Values.fsm.ingress.tls.sslPassthrough.upstreamPort }}
          }
        }
      },

      "gatewayApi": {
        "enabled": {{ .Values.fsm.gatewayApi.enabled }}
      },

      "certificate": {
        {{- if .Values.certManager.enabled }}
        "manager": "cert-manager",
        {{- else }}
        "manager": "archon",
        {{- end }}
        "caBundleName": "{{ .Values.certManager.caBundleName }}",
        "caBundleNamespace": ""
      },

      "cluster": {
        "uid": "",
        "region": "default",
        "zone": "default",
        "group": "default",
        "name": "local",
        "controlPlaneUID": ""
      },

      "serviceLB": {
        "enabled": {{ .Values.fsm.serviceLB.enabled }}
      }
    }