apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.mesh.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  mesh_config.json: |-
    {
      "is-control-plane": true,

      "images": {
        "repository": "{{ .Values.fsm.image.repository }}",
        "pipy-image": {{ include "fsm.pipy.image.wo-repo" . | quote }},
        "proxy-init-image": {{ include "fsm.proxy-init.image.wo-repo" . | quote }},
        "cluster-connector-image": {{ include "fsm.cluster-connector.image.wo-repo" . | quote }},
        "wait-for-it-image": {{ include "fsm.wait-for-it.image.wo-repo" . | quote }}
      },

      "repo": {
        "root-url": {{ include "fsm.repo-service.url" . | quote }},
        "path" : "/repo",
        "api-path": "/api/v1/repo"
      },

      "service-aggregator": {
        "addr": {{ include "fsm.service-aggregator.addr" . | quote }}
      },

      "webhook": {
        "service-name": "{{ .Values.fsm.services.webhook.name }}"
      },

      "ingress": {
        "enabled": {{ .Values.fsm.ingress.enabled }},
        "namespaced": {{ .Values.fsm.ingress.namespaced }},
        "tls": {{ .Values.fsm.ingress.tls }}
      },

      "gateway-api": {
        "enabled": {{ .Values.fsm.gatewayApi.enabled }}
      },

      "certificate": {
        {{- if .Values.certManager.enabled }}
        "manager": "cert-manager"
        {{- else }}
        "manager": "archon"
        {{- end }}
      },

      "cluster": {
        "region": "default",
        "zone": "default",
        "group": "default",
        "name": "local"
      }
    }