apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.mesh.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  mesh_config.json: |-
    {
      "isControlPlane": true,

      "images": {
        "repository": "{{ .Values.fsm.image.repository }}",
        "pipyImage": {{ include "fsm.pipy.image.wo-repo" . | quote }},
        "proxyInitImage": {{ include "fsm.proxy-init.image.wo-repo" . | quote }},
        "clusterConnectorImage": {{ include "fsm.cluster-connector.image.wo-repo" . | quote }},
        "waitForItImage": {{ include "fsm.wait-for-it.image.wo-repo" . | quote }}
      },

      "repo": {
        "rootUrl": {{ include "fsm.repo-service.url" . | quote }},
        "path" : "/repo",
        "apiPath": "/api/v1/repo"
      },

      "serviceAggregator": {
        "addr": {{ include "fsm.service-aggregator.addr" . | quote }}
      },

      "webhook": {
        "serviceName": "{{ .Values.fsm.services.webhook.name }}"
      },

      "ingress": {
        "enabled": {{ .Values.fsm.ingress.enabled }},
        "namespaced": {{ .Values.fsm.ingress.namespaced }},
        "tls": {{ .Values.fsm.ingress.tls }},
        "tlsOffload": {{ not .Values.fsm.ingress.sslPassthrough }},
        "sslPassthrough": {{ .Values.fsm.ingress.sslPassthrough }}
      },

      "gatewayApi": {
        "enabled": {{ .Values.fsm.gatewayApi.enabled }}
      },

      "certificate": {
        {{- if .Values.certManager.enabled }}
        "manager": "cert-manager"
        {{- else }}
        "manager": "archon"
        {{- end }}
      },

      "cluster": {
        "region": "default",
        "zone": "default",
        "group": "default",
        "name": "local"
      }
    }