{{- if and .Values.fsm.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.fsm.ingress.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fsm-namespaced-ingress-rolebinding
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fsm-namespaced-ingress-role
subjects:
  - kind: ServiceAccount
    name: {{ include "fsm.namespacedIngress.serviceAccountName" . }}
    namespace: {{ .Values.metadata.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "fsm-mesh-config-rolebinding-%s" .Values.metadata.namespace }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fsm-mesh-config-role
subjects:
  - kind: ServiceAccount
    name: {{ include "fsm.namespacedIngress.serviceAccountName" . }}
    namespace: {{ .Values.metadata.namespace }}
{{- end }}
{{- end }}