{{- if and .Values.fsm.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.fsm.ingress.namespaced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fsm-namespaced-ingress-role
  namespace: {{ .Values.ObjectMeta.Namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - services
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end }}
{{- end }}