{{- if and .Values.fsm.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.fsm.ingress.namespaced }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fsm.namespacedIngress.serviceAccount.name }}
  namespace: {{ .Values.ObjectMeta.Namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  {{- with .Values.fsm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
