{{- if and .Values.fsm.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.fsm.ingress.namespaced }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "fsm-ingress-pipy-%s" .Values.nsig.metadata.namespace }}
  namespace: {{ .Values.nsig.metadata.namespace }}
  labels:
    {{- include "fsm.ingress-pipy.labels" . | nindent 4 }}
  {{- with .Values.nsig.spec.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nsig.spec.serviceType }}
  {{- $setNodePorts := (or (eq .Values.nsig.spec.serviceType "NodePort") (eq .Values.nsig.spec.serviceType "LoadBalancer")) }}
  ports:
  {{- range .Values.nsig.spec.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ default "TCP" .protocol }}
    targetPort: ingress
    {{- if (and $setNodePorts (not (empty .nodePort))) }}
    nodePort: {{ .nodePort }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "fsm.ingress-pipy.selectorLabels" . | nindent 4 }}
    ingress.flomesh.io/namespaced: {{ .Values.fsm.ingress.namespaced | quote }}
    ingress.flomesh.io/ns: {{ .Values.nsig.metadata.namespace }}
{{- end }}
{{- end }}