name: Build pipy nonroot image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'pipy release tag'
        required: true
        type: string

jobs:
  build-pipy:
    name: Build image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: ["pipy", "pipy-repo"]
        tag: [ "nonroot", "debug-nonroot" ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.FLOMESH_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FLOMESH_DOCKERHUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.3.0
        with:
          images: flomesh/${{ matrix.name }}
          tags: |
            type=raw,${{ inputs.tag }}-${{ matrix.tag }}

      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./dockerfiles/${{ matrix.name }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            DISTROLESS_TAG=${{ matrix.tag }}
            PIPY_VERSION=${{ inputs.tag }}
          
