# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# hadoint is a Dockerfile linter written in Haskell
# that helps you build best practice Docker images.
# More details at https://github.com/hadolint/hadolint

name: Hadolint

on:
  push:
    branches: [ "main", "release-v0.1", "release-v0.2" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main",  "release-v0.1", "release-v0.2" ]

permissions:
  contents: read

jobs:
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-22.04
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    strategy:
      matrix:
        id: [ "manager", "proxy-init", "ingress-pipy", "pipy" ]
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ./dockerfiles/${{ matrix.id }}/Dockerfile
          format: sarif
          output-file: hadolint-${{ matrix.id }}-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-${{ matrix.id }}-results.sarif
          wait-for-processing: true
