name: release

on:
  release:
    types:
      - created

jobs:     
  build_and_push_images:
    name: Build and Release image to Quay.io
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        id: [ "manager", "proxy-init", "cluster-connector", "bootstrap", "ingress-pipy" ]
    steps:
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.4'
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to Quay.io
      uses: docker/login-action@v2.1.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set version
      run: |
        cat VERSION >> $GITHUB_ENV

    - name: Package Helm Charts
      run: make charts-tgz-rel

    - name: Docker meta - ${{ matrix.id }}
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v4.1.1
      with:
        images: quay.io/flomesh/fsm-${{ matrix.id }}-ubi8
        tags: |
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=sha,format=long
        flavor: |
          latest=auto
        labels: |
          name=fsm-${{ matrix.id }}-ubi8
          vendor=flomesh.io
          maintainer=LinYang
          version=${{ env.APP_VERSION }}
          release=1
          summary=fsm-${{ matrix.id }}
          description=fsm-${{ matrix.id }}

    - name: Build and Push - ${{ matrix.id }}
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./dockerfiles/${{ matrix.id }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ (github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )) }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

  build_tools:
    name: Build tools images
    runs-on: ubuntu-20.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Quay.io
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Push toolbox
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./dockerfiles/toolbox/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/flomesh/toolbox-ubi8:1.2.0
          labels: |
            name=toolbox-ubi8
            vendor=flomesh.io
            maintainer=LinYang
            version=1.2.0
            release=1
            summary=toolbox
            description=toolbox

      - name: Build and Push curl
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./dockerfiles/curl/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/flomesh/curl-ubi8:7.84.0
          labels: |
            name=curl-ubi8
            vendor=flomesh.io
            maintainer=LinYang
            version=7.84.0
            release=1
            summary=curl
            description=curl
