name: release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build_and_push_images:
    name: Build and Release image to Docker Hub
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        id: [ "manager", "proxy-init", "cluster-connector", "bootstrap", "ingress-pipy" ]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.FLOMESH_DOCKERHUB_USERNAME }}
        password: ${{ secrets.FLOMESH_DOCKERHUB_PASSWORD }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker meta - ${{ matrix.id }}
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v4.0.1
      with:
        images: flomesh/fsm-${{ matrix.id }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
        flavor: |
          latest=auto

    - name: Build and Push - ${{ matrix.id }}
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        file: ./dockerfiles/${{ matrix.id }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ (github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )) }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

  release_project:
    name: Create Github Release
    runs-on: ubuntu-20.04
    needs:
    - build_and_push_images
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Install packages
      run: sudo apt-get install -y git make

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
        git_push_gpgsign: true

    - name: Run GoReleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      run: make gh-release

    - name: Install Helm
      uses: azure/setup-helm@v2.1
      with:
        version: v3.8.2

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


#    - name: Release
#      uses: softprops/action-gh-release@v1
#      if: ${{ (github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )) }}
#      with:
#        body_path: dist/CHANGELOG.md
#        files: |
#          artifacts/fsm.yaml
#          etc/cert-manager-v1.5.3.yaml
#          dist/*.tar.gz
#          dist/*.zip
#          dist/checksum.txt
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}